### ISSUE TITLE
Add application/json Header

### ISSUE THREAD

**Issue by SergejKasper** [getbible/Bibles#1]
Hi,

Thank you for creating the GetBible API!
I want to use it for a project in Apologetics, but can't retrieve the data with JSONP as the content-type seems to be text/html (http://stackoverflow.com/questions/3467404/chrome-says-resource-interpreted-as-script-but-transferred-with-mime-type-text). Could you please set it to "Content-Type: application/x-javascript" if that's the case?

God bless you!
Sergej

**Comment by Llewellynvdm** [comment]
Amazing news, have a look at https://github.com/getbible/v1#getbible-api-v1 the new easy expansion of the getBible API
