### ISSUE TITLE
A GET request results in an invalid JSON. 

### ISSUE THREAD

**Issue by immanuelnoel** [getbible/Bibles#12]
Query the following URL: 
http://getbible.net/json?passage=Acts%2015:1-5&version=akjv

Returns the following JSON, Has a "(" at the beginning, and ");" at the end. 

({"book":[{"book_ref":"Ac","book_name":"Acts","book_nr":"44","chapter_nr":"15","chapter":{"1":{"verse_nr":"1","verse":"And certain men which came down from Judaea taught the brothers, and said, Except you be circumcised after the manner of Moses, you cannot be saved.\r\n"},"2":{"verse_nr":2,"verse":"When therefore Paul and Barnabas had no small dissension and disputation with them, they determined that Paul and Barnabas, and certain other of them, should go up to Jerusalem to the apostles and elders about this question.\r\n"},"3":{"verse_nr":3,"verse":"And being brought on their way by the church, they passed through Phenice and Samaria, declaring the conversion of the Gentiles: and they caused great joy to all the brothers.\r\n"},"4":{"verse_nr":4,"verse":"And when they were come to Jerusalem, they were received of the church, and of the apostles and elders, and they declared all things that God had done with them.\r\n"},"5":{"verse_nr":5,"verse":"But there rose up certain of the sect of the Pharisees which believed, saying, That it was needful to circumcise them, and to command them to keep the law of Moses.\r\n"}}}],"direction":"LTR","type":"verse","version":"akjv"});

**Comment by immanuelnoel** [comment]
Ah! Came across the solution. Closing this now.
https://github.com/getbible/Joomla-3-Component/issues/17

And, absolutely great work! Keep it up!

**Comment by Llewellynvdm** [comment]
Amazing news, have a look at https://github.com/getbible/v1#getbible-api-v1 the new easy expansion of the getBible API
