### ISSUE TITLE
The API returns complete bible if requesting for an unknown Book/Verse

### ISSUE THREAD

**Issue by abussl** [getbible/Bibles#13]
I found maybe a little bug in your API. If i call the following query with a non-existing  book/verse, so the API returns the complete bible.

https://getbible.net/json?passage=1KN3:88&v=elberfelder1905 (1KN3:88 doesn't exist)

I'm not sure, if this in an error. I think, if i make a query with a non-existing verse, i should get "NULL" (or better a good answer message), or not?
Because if i call  https://getbible.net/json?passage=1KN3:88 only (without &v=), i get "NULL". This is different.

And by the way: info@getbible.net isn't available. I got an error (retry timeout exceeded)...

**Comment by Llewellynvdm** [comment]
We are working on new API version 2 based on the Crosswire modules [as explained here](https://github.com/getbible/Unbound-Biola/issues/16#issuecomment-569303945).

So Version 2 should be out soon, and I trust it will have those errors resolved.
