### ISSUE TITLE
Verse Mistake In NCV

### ISSUE THREAD

**Issue by sinri** [getbible/Bibles#14]
The first verse of Genesis of NCV is wrong, 
which takes the paragraph title as the first verse of chapter one.
As I observe, errors of this kind are there throughout the text.
It is better to fix them.

e.g.
----

01O||1||1||创造天地万物
01O||1||2||地是空虚混沌；深渊上一片黑暗；　神的灵运行在水面上。

here `创造天地万物` is just a title, not the verse 1.

**Comment by Llewellynvdm** [comment]
Can you check this version: https://getbible.net/v2/cns/1.json

**Comment by sinri** [comment]
Great Job, seems ok now

**Comment by Llewellynvdm** [comment]
We are working on new API version 2 based on the Crosswire modules [as explained here in more details](https://github.com/getbible/Unbound-Biola/issues/16#issuecomment-569303945).

So Version 2 should be out soon, and I trust it will have those errors resolved.
