### ISSUE TITLE
1 Chronicles 19 is not right

### ISSUE THREAD

**Issue by raxok63777** [getbible/Bibles#15]
1 Chronicles 19 should have 19 verses in the KJV version, not 18.
Also, the second verse is wrong.

**Comment by Llewellynvdm** [comment]
We are working on new API version 2 based on the Crosswire modules [as explained here](https://github.com/getbible/Unbound-Biola/issues/16#issuecomment-569303945).

So Version 2 should be out soon, and I trust it will have those errors resolved.
