### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by francismakes** [getbible/Bibles#2]
Hi @Llewellynvdm!

Thanks for your work on `Bibles`. I noticed that there is not a LICENSE present for this repository. If I wanted to use any file from this repo for building an application, where can I obtain the proper permissions before using it? 

Thanks! :book:

**Comment by Llewellynvdm** [comment]
These Bibles are all to my knowledge in the public domain, most of the translations are provided by The Unbound Bible https://unbound.biola.edu/. (some translations were given by permission to the developing community www.4-14.org.uk/xml-bible-web-service-api)

For more information on a specific translation, google should be a good place to start your search.

Our policy of distribution is to insure that the actual Text can not easily be changed from inside our application https://github.com/getbible/Joomla-3-Component. We also want to make sure that the Word of God can go out as free and wide as possible unrestrained.

If you know of any other translations also in the public domain please let us know and we will add it to this repository.

**Comment by francismakes** [comment]
@Llewellynvdm I appreciate the information. I will take a closer look at those mentioned resources. Thanks!

**Comment by Xsmael** [comment]
does that mean i can freely use one of the bibles available here in my software ?

**Comment by Llewellynvdm** [comment]
Hi, each Bible has its own license file, if you could keep those details available in your software, I am sure it should be okay.

For example:
[English__King_James_Version__kjv__LTR.txt](https://github.com/getbible/Bibles/blob/master/English__King_James_Version__kjv__LTR.txt)
[English__King_James_Version__kjv__LTR-copyright.html](https://github.com/getbible/Bibles/blob/master/English__King_James_Version__kjv__LTR-copyright.html)

So yes you can use these Bible in your own software, just keep the copyright notice in place.

> Please do not make money with the Bible! Keep it free as you are using it for free!!

> IF you plan on making money with these translations. Then please make contributions to these publisher of the various translations you may be using. 

> I do not think it is right for them to do the work (of translation), and not get financial support when you make money of their work.

**Comment by Xsmael** [comment]
Yes i totally agree i do not plan to make money out of these, its one feature of my software wich is free and open source, i'll be releasing it very soon.

Thanks & God bless you!
