### ISSUE TITLE
A list of Valid abbreviations

### ISSUE THREAD

**Issue by drmaposa** [getbible/Bibles#3]
Hi @Llewellynvdm

Thank you very much for such a tremendous effort to make the Word of God available world wide

May I know the abbreviations of the English version

thanks

**Comment by Llewellynvdm** [comment]
All the English versions abbreviations are as follow: 

- King James Version (**kjv**)
- KJV Easy Read (**akjv**)
- American Standard Version (**asv**)
- Amplified Version (**amp**)
- Basic English Bible (**basicenglish**)
- Darby (**darby**)
- New American Standard (**nasb**)
- Young's Literal Translation (**ylt**)
- World English Bible (**web**)
- Webster's Bible (**wb**)

If you are looking for the Books abbreviations please watch this video:
[book names](https://getbible.net/main-component?tab=5)

Also check out this json file:
[app page defaults](https://getbible.net/media/com_getbible/json/cpanel_default.json)

**Comment by Llewellynvdm** [comment]
Amazing news, have a look at https://github.com/getbible/v1#getbible-api-v1 the new easy expansion of the getBible API
