### ISSUE TITLE
Feature request: Spanish Reina Valera 1960

### ISSUE THREAD

**Issue by nicolasguzca** [getbible/Bibles#5]
Hello, first of all thank you for this amazing bible translations. We will love to implement this in our app but the bible version that is commonly used in Latin America is Reina Valera 1960. Do you have this bible version available? Do we need to purchase a license?

Thank you and God bless,

Nick

P.S ( I wrote you some emails to info@getbible.net but they all bounced back, sorry to write this as an issue)

**Comment by Llewellynvdm** [comment]
Hi Nick

I did get your email :) sorry for the delay in reply...

The translations on this repository is all we have at this time, and they are all able to be used for free... there are some licensing files available in relation to various translations.

The translation (**Latin America - Reina Valera 1960**) you are looking for is not yet part of our repository... tell me is that version available in a free way? I mean can you get that translation digitally and may we use it in the same capacity as the other translations in repository? If you can secure this permission and provide the needed files we will add it here and make it available on getBible.net and on all websites that use getBible.

We would like to stay with translations that are free for all to use, and so we don't sell licensing. 

You may know this but getBible is a Joomla component that you can install on any Joomla website, the API is therefore also free and portable to any website. Take a look at these videos to get a better understanding. https://getbible.net/main-component _(*four videos)_

You will see that the application has the option of installing a translation from a local folder... this means if you can not secure permission to add the translation to the getBible repository, but may have permission to use it your self.. you can install it on your own instance of getBible.

Let me know if you have any further questions.

**Comment by nicolasguzca** [comment]
Hello! 
We do have the bible in .sql format, and have secured permission for our app. Is it posible to convert it to the getBible format? I personally love this API :)

Thanks

**Comment by Llewellynvdm** [comment]
So you have permission to use it but only on your website/app?

**Comment by nicolasguzca** [comment]
Yes, only on our app. They gave it to us in a SQL Format. If you could tell me how I can convert it to the format getBible uses that will be a huge help.

**Comment by Llewellynvdm** [comment]
Well the format to install is [explained in the videos](https://getbible.net/main-component) I gave you. To write a script to convert the sql into that format should not be that hard. If you are not able to do that, you can send the SQL [to me](mailto:llewellyn@vdm.io) and I can convert it for you.

**Comment by nicolasguzca** [comment]
Thank you I will check them out, if I run into any trouble I'll get back to you. :)
