### ISSUE TITLE
Api returning invalid json format

### ISSUE THREAD

**Issue by TinasheMzondiwa** [getbible/Bibles#7]
Firstly thank you for the great work.

Right now it looks like the api is not returning a valid json format.
From this call :  https://getbible.net/json?scripture=Luke%207:2&v=aov
I get below response:
`({"book":[{"book_ref":"Lk","book_name":"Lukas","book_nr":"42","chapter_nr":"7","chapter":{"2":{"verse_nr":"2","verse":"En die dienskneg van 'n sekere hoofman oor honderd, wat vir hom baie werd was, was ongesteld en het op sterwe gel\u00ea."}}}],"direction":"LTR","type":"verse","version":"aov"});
`
I believe the '(' and ');' should not be there. Is this correct?

**Comment by Llewellynvdm** [comment]
Please view this issue https://github.com/getbible/Joomla-3-Component/issues/14

**Comment by Llewellynvdm** [comment]
Amazing news, have a look at https://github.com/getbible/v1#getbible-api-v1 the new easy expansion of the getBible API
