### ISSUE TITLE
can't access api because of cors issue

### ISSUE THREAD

**Issue by jajourda** [getbible/Bibles#8]
Here is the javascript:
![image](https://user-images.githubusercontent.com/1839603/27637119-8826b6ec-5bdc-11e7-9d0e-8f774b329ba6.png)

Here is the response:
![image](https://user-images.githubusercontent.com/1839603/27637111-8158d6e2-5bdc-11e7-9f71-fb85a1d7e51c.png)

**Comment by jajourda** [comment]
I'm a loser 👍 

you mean i have to use my eyes? 
😛 
![image](https://user-images.githubusercontent.com/1839603/27637422-ac2a8a0e-5bdd-11e7-9b55-ce7125df2846.png)


It works beautifully. closing this.

**Comment by Llewellynvdm** [comment]
Amazing news, have a look at https://github.com/getbible/v1#getbible-api-v1 the new easy expansion of the getBible API
