### ISSUE TITLE
version: LEB Lexham English Bible?

### ISSUE THREAD

**Issue by jajourda** [getbible/Bibles#9]
Would you be able to include the LEB?

http://lexhamenglishbible.com/

the license seems to permit it being used:

http://lexhamenglishbible.com/license/

**Comment by Llewellynvdm** [comment]
You are welcome to add it to your own install of getBIble, we will not be adding it to our public repository.

Please watch the following videos if you have any questions: https://getbible.net/main-component

There are four videos to watch on this page.

**Comment by jajourda** [comment]
sorry, curious; why wouldn't you add it?

*Thanks,*
[image: facebook logo] <https://www.facebook.com/TripleH3lix>[image:
twitter logo] <https://twitter.com/H3lixTriple>[image: linkedin logo]
<https://www.linkedin.com/in/triple-h3lix-creative-147b87117?trk=hp-identity-name>
* :josh@helix.vision* <josh@helix.vision>
* :843.408.6280* <18434086280>

**Comment by Llewellynvdm** [comment]
Sure, no reason to be sorry. You are welcome to add it to your own install of the [getBible API](https://github.com/getbible/Joomla-3-Component) as explained in those video tutorials. 

So you don't need to use this repository at all. You can really setup our own API with the [getBible component](https://github.com/getbible/Joomla-3-Component). 

This we believe is very empowering and therefore giving us all the liberty to only add translations to our repositories that we would like to use. 

Lastly we do not have clearing/peace in our hearts about this translation _(please do your own research)_, so we do not want to use it. If other would like to they can like I explained setup their own API with the [getBible component](https://github.com/getbible/Joomla-3-Component).

Thank you for your understanding.
